### ISSUE TITLE
[Feature Request] Add globalProperty options

### ISSUE THREAD

**Issue by alex-marczinek** [BeerMoneyDev/nest-openapi-tools#11]
Currently, there's an option to pass --additional-properties, but no option to pass --global-property.

As a workaround you can currently use something like `additionalProperties: ' --global-property skipFormModel=false',`.
But it would be nice to have proper support and add an option such as `globalProperty: 'skipFormModel=false'`.

**Comment by KerryRitter** [comment]
Great idea. I'll add this ASAP!

**Comment by KerryRitter** [comment]
Released in 4.0.0 - thanks Alex!
