### ISSUE TITLE
Add support for nestjs v8

### ISSUE THREAD

**Issue by alex-marczinek** [BeerMoneyDev/nest-openapi-tools#13]
Currently only nestjs v7 is supported. However this is currently blocking me from updating my service to nestjs v8. Do you have any plans to release a new version supporting nestjs v8?

**Comment by KerryRitter** [comment]
Hey Alex, sorry I've been away for vacation. Working on getting my PR for this merged asap.

**Comment by alex-marczinek** [comment]
Hi Kerry, thank you very much for taking care of this. Do you already have any idea how long it will take?

**Comment by alex-marczinek** [comment]
@KerryRitter thank you very much for getting this merged so quickly. Is there anything left I can do to help you get a release done?

**Comment by KerryRitter** [comment]
@alex-marczinek 4.0.0 should be out the door!

**Comment by KerryRitter** [comment]
Closing this out - let me know if you have any issues.
