### ISSUE TITLE
The `outputFolderPath` field is not working

### ISSUE THREAD

**Issue by andreymyssak** [BeerMoneyDev/nest-openapi-tools#34]
Based on the condition in line 42 of the code, it will always use `outputFolderPath` by default, no matter what we pass in.
 
https://github.com/BeerMoneyDev/nest-openapi-tools/blob/ddc2d889cd1980fbfd4f1acde2e63954d6afdd6a/src/openapi-nest.factory.ts#L38-L64

**Comment by ronniehicks** [comment]
@andreymyssak good catch! That is a bug, feel free to submit a PR to correct it if you can. If not we will get to it when we can. 

Thanks!

**Comment by andreymyssak** [comment]
@ronniehicks, I've opened a PR https://github.com/BeerMoneyDev/nest-openapi-tools/pull/35, feel free to review it.
